"""BUD-1: unique budget target per category

Revision ID: 8b706faf71d8
Revises: 60f67d2f81da
Create Date: 2026-07-12 13:19:26.078767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b706faf71d8'
down_revision: Union[str, Sequence[str], None] = '60f67d2f81da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_budget_target_user_category', 'budget_targets', ['user_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_budget_target_user_category', 'budget_targets', type_='unique')
    # ### end Alembic commands ###
